//
// Created by Archishmaan Peyyety on 2/14/23.
//
const int PREVIOUS_BEST_MOVE_BONUS = 1'000'000;
const int PROMOTION_BONUS = PREVIOUS_BEST_MOVE_BONUS / 10;
const int MVV_LVA_BONUS = PROMOTION_BONUS / 10;
const int KILLER_MOVE_BONUS = MVV_LVA_BONUS / 10;
const int HISTORY_BONUS = -(KILLER_MOVE_BONUS / 10);
const int IN_OPP_PAWN_TERRITORY_PENALTY = -350;

const short NKILLERS = 2;
